services:
  - type: web
    name: aa-fundir-api
    runtime: docker
    plan: starter
    dockerfilePath: ./apps/api/Dockerfile
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 4000
      - key: REFRESH_TOKEN
        sync: false

  - type: web
    name: aa-fundir-web
    runtime: static
    rootDir: apps/web
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        sync: false
